WITH raw_orders AS (
    SELECT * FROM {{ source('olist_raw', 'ORDERS') }}
)

SELECT
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_STATUS,
    -- Perform the date functions on the raw timestamp column
    DATE_TRUNC('month', CAST(ORDER_PURCHASE_TIMESTAMP AS TIMESTAMP)) AS ORDER_MONTH,
    EXTRACT(YEAR FROM CAST(ORDER_PURCHASE_TIMESTAMP AS TIMESTAMP)) AS ORDER_YEAR,
    -- Keep our clean, casted timestamps in UPPERCASE
    CAST(ORDER_PURCHASE_TIMESTAMP AS TIMESTAMP) AS ORDER_PURCHASE_AT,
    CAST(ORDER_APPROVED_AT AS TIMESTAMP) AS ORDER_APPROVED_AT,
    CAST(ORDER_DELIVERED_CARRIER_DATE AS TIMESTAMP) AS ORDER_LEFT_CARRIER_AT,
    CAST(ORDER_DELIVERED_CUSTOMER_DATE AS TIMESTAMP) AS ORDER_DELIVERED_AT,
    CAST(ORDER_ESTIMATED_DELIVERY_DATE AS TIMESTAMP) AS ORDER_ESTIMATED_DELIVERY_AT
FROM raw_orders